model:
    arch: frrnB
data:
    dataset: railanomalies
    val_split: test
    img_rows: 512
    img_cols: 512
    path: /home/stanik/rtis_lab/data/rtis-rail-rgba2rgb/custom_split/
training:
    batch_size: 1