model:
    arch: frrnB
data:
    dataset: cityscapes_rs19
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    path: /home/stanik/rtis_lab/data/Cityscapes/
training:
    train_iters: 160000
    batch_size: 2
    n_workers: 1
    val_interval: 1500
    print_interval: 1500
    optimizer:
        name: adam
        lr: 1.0e-3
    augmentations:
        brightness: 1.12                             
        saturation: 1.12                                
        contrast: 1.12                                                       
        rotate: 14                                   
        vflip: 0.3 

    l_rate: 1.0e-3
    lr_schedule: 
        name: cosine_annealing
        T_max: 500
    momentum: 0.99
    weight_decay: 0.0005
    visdom: False
    loss:
        name: cross_entropy
    resume: null
