model:
    arch: frrnB
data:
    dataset: railsem19
    train_split: train
    val_split: validation
    img_rows: 512
    img_cols: 512
    path: /home/stanik/rtis_lab/data/RailSem19/custom_split/
training:
    train_iters: 300000
    batch_size: 16
    n_workers: 4
    val_interval: 1500
    print_interval: 25
    optimizer:
        name: adam
        lr: 1.0e-3
    augmentations:
        brightness: 1.12                            
        saturation: 1.12                                
        contrast: 1.12                                                 
        rotate: 14                                 
        vflip: 0.5
    l_rate: 1.0e-5
    lr_schedule: 
        name: cosine_annealing
        T_max: 500
    momentum: 0.99
    weight_decay: 0.0005
    visdom: False
    loss:
        name: cross_entropy
    resume: /home/stanik/repos/pytorch-semseg/runs/frrnB_cityscapes1/bs_8_160k_iter/frrnB_cityscapes_rs19_best_model.pkl
