model:
    arch: frrnB
data:
    dataset: railanomalies
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    path: /home/stanik/rtis_lab/data/rtis-rail-2022v8/custom_split/
training:
    train_iters: 350000
    batch_size: 10
    n_workers: 4
    val_interval: 1
    print_interval: 25
    optimizer:
        name: adam
        lr: 2.0e-5
    augmentations:
        brightness: 1.12                            
        saturation: 1.12                                
        contrast: 1.12                                                 
        rotate: 14                                 
        vflip: 0.5
    l_rate: 2.0e-5
    lr_schedule: 
        name: cosine_annealing
        T_max: 500
    momentum: 0.99
    weight_decay: 0.0005
    visdom: False
    loss:
        name: cross_entropy
    resume: /home/stanik/repos/pytorch-semseg/runs/frrnb_rs19/61942/frrnB_railsem19_best_model.pkl
