model:
    arch: frrnB
data:
    dataset: railsem19
    train_split: trainVal
    val_split: test
    img_rows: 512
    img_cols: 512
    path: /home/stanik/rtis_lab/data/RailSem19/custom_split/
training:
    train_iters: 350000
    batch_size: 10
    n_workers: 2
    val_interval: 1
    print_interval: 1500
    optimizer:
        name: adam
        lr: 3.0e-4
    augmentations:
        brightness: 1.12                            
        saturation: 1.12                                
        contrast: 1.12                                                 
        rotate: 14                                 
        vflip: 0.5
    l_rate: 3.0e-4
    lr_schedule: 
        name: cosine_annealing
        T_max: 500
    momentum: 0.99
    weight_decay: 0.0005
    visdom: False
    loss:
        name: cross_entropy
    resume: /home/stanik/repos/pytorch-semseg/runs/frrnB_cityscapes1/82229/frrnB_cityscapes_rs19_best_model.pkl
