model:
    arch: frrnB
data:
    dataset: railsem19
    val_split: test
    img_rows: 512
    img_cols: 512
    path: /home/stanik/rtis_lab/data/RailSem19/custom_split/
training:
    batch_size: 1